###
GET {{host}}/_article/notice/list

###
GET {{host}}/_article/-1

### 새로운 글 등록
POST {{host}}/_article
Content-Type: application/json

{
  "category": "notice",
  "title": "TEST",
  "user": {
    "id": -1,
    "username": "test"
  },
  "author": "hello",
  "email": "hello@test.com",
  "content": "<h1>TITLE</h1><p>hello</p>",
  "extra": {
    "width": "1234px",
    "height": "4321px",
    "square": false,
    "axis": 4
  },
  "attachFiles": [
    {
      "id": "-1"
    },
    {
      "id": "-2"
    }
  ]
}

### edit articles
PUT {{host}}/_article
Content-Type: application/json

{
  "id": -1,
  "removal": false,
  "bunch": -1,
  "sequel": 0,
  "depth": 0,
  "category": "notice",
  "user": {
    "id": -1,
    "removal": false,
    "username": "tester"
  },
  "author": "anonymity",
  "email": "anonymous@xxx.xyz",
  "secret": false,
  "read": 0,
  "title": "data 1",
  "content": null,
  "attachFiles": [
    {
      "id": "-1",
      "name": "A.png",
      "path": "/root/image1",
      "size": 0,
      "type": null,
      "read": 0,
      "removal": false
    },
    {
      "id": "-2",
      "name": "B.png",
      "path": "/root/image2",
      "size": 0,
      "type": null,
      "read": 0,
      "removal": false
    }
  ],
  "extra": {
     "width": "1234px",
     "height": "4321px",
     "rectangle": true,
     "axis": 4
   }
}


### 게시물 삭제
DELETE {{host}}/_article/1
