GET {{host}}/_authority?id=0

###
GET {{host}}/_authority/team

###
POST {{host}}/_authority/team
Content-Type: application/json

[
  {
    "team": {
      "id": "-912"
    },
    "authority": {
      "id": "-10"
    }
  }
]

### get authority by each user
GET {{host}}/_authority/user/-1

###
GET {{host}}/_authority/authorized

###
GET {{host}}/_authority/authorized/tester
