POST {{host}}/_board/notice
Content-Type: application/json

{
  "title": "TEST",
  "content": {
    "body": "<h1>TITLE</h1><p>some text</p>"
  },
  "removeFileIds": [
    "key1",
    "key2",
    "key3"
  ]
}

