ddul:
  apply-security: true


spring:
  data:
    web:
      pageable:
        default-page-size: 5

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./ddul;AUTO_SERVER=TRUE"
    username: "sa"
    password: ""

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations:
        - "classpath*:ddul-schema.sql"
      data-locations:
        - "classpath*:ddul-data.sql"

  h2:
    console:
      enabled: true
      path: "/h2-console"

  messages:
    cache-duration: 3


logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.type.BasicTypeRegistry: WARN


springdoc:
  api-docs:
    path: "/docs"


server.port: 8090

