spring:

  data:
    web:
      pageable:
        default-page-size: 5

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations:
        - "classpath:ddul-schema.sql"

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./ddul;AUTO_SERVER=TRUE;Mode=Oracle"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true
      path: "/h2-console"


# p6spy (SQL Logging)
decorator.datasource.enabled: true


logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"
  level:
    org.hibernate.type: TRACE
    org.hibernate.type.BasicTypeRegistry: WARN


server.port: 8090
