spring:
  profiles:
    active: "development"

  main:
    banner-mode: off

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none


mybatis:
  type-handlers-package: "io.github.greennlab.ddul.mybatis.handlers"
  configuration-properties:
    pagination-wrapped-sql: "${sql} LIMIT ${size} OFFSET (${size} * ${page})"
    pagination-counted-sql: "SELECT count(1) FROM ( ${sql} )"


graphql:
  servlet:
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
  graphiql:
    enabled: true
    cdn:
      enabled: true




ddul:
  file-storage: file-storage/

# p6spy (SQL Logging)
decorator.datasource.enabled: true


logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"

