spring:

  data:
    web:
      pageable:
        default-page-size: 5

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./ddul;AUTO_SERVER=TRUE;Mode=Oracle"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true
      path: "/h2-console"

  messages:
    cache-duration: 3


logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.type.BasicTypeRegistry: WARN


server.port: 8090

