spring:

  messages:
    cache-duration: 3

  data:
    web:
      pageable:
        default-page-size: 5

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./ddul;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;"
    username: "sa"
    password: "11"
  h2:
    console:
      enabled: true
      path: "/h2-console"

  jpa:
    hibernate:
      ddl-auto: update
