spring:

  messages:
    cache-duration: 3

  data:
    web:
      pageable:
        default-page-size: 5

  sql:
    init:
      schema-locations:
        - "classpath:db.sql"

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./db;AUTO_SERVER=TRUE"
    username: "sa"
    password: "11"
  h2:
    console:
      enabled: true
      path: "/h2-console"

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
