spring:
  profiles:
    default: "development"

  mvc:
    view:
      prefix: "/WEB-INF/pages/"
      suffix: ".jsp"


mybatis:
  type-aliases-package: "ddul"
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR


logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"
  level:
    com.solideos.cms: DEBUG


server.port: 8089

