spring:
  profiles:
    active: "development"

  main:
    banner-mode: off

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  data:
    web:
      pageable:
        default-page-size: 5

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./ddul;AUTO_SERVER=TRUE;Mode=Oracle"
    username: "sa"
    password: ""

  h2:
    console:
      enabled: true
      path: "/h2-console"


mybatis:
  configuration-properties:
    pagination-wrapped-sql: "${sql} LIMIT ${size} OFFSET (${size} * ${page})"
    pagination-counted-sql: "SELECT count(1) FROM ( ${sql} )"


file.storage:
  path: "file-storage/"


logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"
  level:
    org.hibernate.type: TRACE
    org.hibernate.type.BasicTypeRegistry: WARN

server.port: 8090

