spring:
  profiles:
    active: "development"

  main:
    banner-mode: off

  sql:
    init:
      continue-on-error: true
      schema-locations:
        - "classpath*:ddul-schema.sql"

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none


mybatis:
  configuration-properties:
    pagination-wrapped-sql: "${sql} LIMIT ${size} OFFSET (${size} * ${page})"
    pagination-counted-sql: "SELECT count(1) FROM ( ${sql} )"


file.storage:
  path: "file-storage/"


# p6spy (SQL Logging)
decorator.datasource.enabled: true


logging:
  pattern:
    console: "%highlight(%-5level) %d{HH:mm:ss.SSS}[%green(%thread)]%magenta(%logger{36}) %msg %n"

