BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE ID_GENERATOR_SQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
CREATE SEQUENCE ID_GENERATOR_SQ START WITH 1;


--
-- User entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USR CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE USR
(
    ID           NUMBER PRIMARY KEY,
    USERNAME     VARCHAR2(32) NOT NULL UNIQUE,
    PASSWORD     VARCHAR2(256),
    TEAM_ID      NUMBER(19),
    EMAIL        VARCHAR2(128),
    NAME         VARCHAR2(64),
    DEPT         NUMBER(19),
    GRADE        VARCHAR2(64),
    PASSWORD_EXPIRED TIMESTAMP,
    HIRED        TIMESTAMP,
    USE          CHAR(1)   DEFAULT 'Y' CHECK (USE = 'Y' OR USE = 'N'),
    -- auditors
    REMOVAL      CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR      VARCHAR2(32) ,
    UPDATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER      VARCHAR2(32)
);
COMMENT ON TABLE USR IS '사용자';
COMMENT ON COLUMN USR.USERNAME IS '사용자명(로그인 ID)';
COMMENT ON COLUMN USR.PASSWORD_EXPIRED IS '비밀번호 만료일시';
COMMENT ON COLUMN USR.NAME IS '성명';
COMMENT ON COLUMN USR.DEPT IS '부서';
COMMENT ON COLUMN USR.GRADE IS '직급';
COMMENT ON COLUMN USR.USE IS '잠김';

INSERT INTO USR (ID, USERNAME, PASSWORD, EMAIL, NAME, PASSWORD_EXPIRED) SELECT * FROM (
SELECT -1, 'tester', '{noop}test123$', 'tester@test.com', 'foo', ADD_MONTHS(SYSTIMESTAMP, 3) FROM DUAL UNION ALL
SELECT -2, 'leader', '{noop}lead123$', 'leader@test.com', 'bar', ADD_MONTHS(SYSTIMESTAMP, 3) FROM DUAL
) WHERE NOT EXISTS( SELECT * FROM USR);

--
-- Team Entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TEAM CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE TEAM
(
    ID      NUMBER(19) PRIMARY KEY,
    PID     NUMBER(19),
    NAME    VARCHAR2(64),
    ORD     NUMBER(10)       DEFAULT 0,
    -- auditors
    REMOVAL CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR VARCHAR2(32) ,
    UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER VARCHAR2(32)
);
COMMENT ON TABLE TEAM IS '부서';
COMMENT ON COLUMN TEAM.ORD IS '정렬순서';

INSERT INTO TEAM (ID, PID, NAME, ORD) SELECT * FROM (
SELECT -900, NULL, '회장실', 0 FROM DUAL UNION ALL
SELECT -910, -900, '미래전략실', 0 FROM DUAL UNION ALL
SELECT -911, -910, '실장실', 0 FROM DUAL UNION ALL
SELECT -912, -910, '차장실', 1 FROM DUAL UNION ALL
SELECT -913, -912, '준법경영실', 1 FROM DUAL UNION ALL
SELECT -914, -912, '전략1팀', 0 FROM DUAL UNION ALL
SELECT -915, -912, '전략2팀', 1 FROM DUAL UNION ALL
SELECT -916, -912, '경영지원실', 2 FROM DUAL UNION ALL
SELECT -920, -900, 'DS', 1 FROM DUAL UNION ALL
SELECT -921, -920, '메모리 사업부', 0 FROM DUAL UNION ALL
SELECT -922, -920, '시스템 SI 사업부', 1 FROM DUAL UNION ALL
SELECT -923, -920, '파운드리 사업부', 2 FROM DUAL UNION ALL
SELECT -930, -900, 'CE', 3 FROM DUAL UNION ALL
SELECT -931, -930, '디스플레이 사업부', 1 FROM DUAL UNION ALL
SELECT -932, -930, '생활가전 사업부', 0 FROM DUAL UNION ALL
SELECT -933, -930, '의료기기 사업부', 2 FROM DUAL UNION ALL
SELECT -940, -900, 'IM', 2 FROM DUAL UNION ALL
SELECT -941, -940, '무선 사업부', 0 FROM DUAL UNION ALL
SELECT -942, -940, '네트워크 사업부', 1 FROM DUAL
) WHERE NOT EXISTS(SELECT * FROM TEAM);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAP_USER_TEAM CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE MAP_USER_TEAM
(
    ID      NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19),
    TEAM_ID NUMBER(19),
    -- auditors
    REMOVAL CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR VARCHAR2(32) ,
    UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER VARCHAR2(32)
);


COMMENT ON TABLE MAP_USER_TEAM IS '사용자-부서 매핑';


--
-- Authority Entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE AUTHORITY CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE AUTHORITY
(
    ID      NUMBER(19) PRIMARY KEY,
    PID     NUMBER(10),
    ROLE    VARCHAR2(32) NOT NULL UNIQUE,
    -- auditors
    REMOVAL CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR VARCHAR2(32) ,
    UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER VARCHAR2(32)
);
COMMENT ON TABLE AUTHORITY IS '권한';
COMMENT ON COLUMN AUTHORITY.ROLE IS '권한 이름';

INSERT INTO AUTHORITY (ID, PID, ROLE) SELECT * FROM (
SELECT 0, NULL, 'ADMIN' FROM DUAL UNION ALL
SELECT -1, 0, 'BOSS' FROM DUAL UNION ALL
SELECT -2, -1, 'OFFICER' FROM DUAL UNION ALL
SELECT -3, -2, 'MINION' FROM DUAL UNION ALL
SELECT -4, -3, 'ROOKIE' FROM DUAL UNION ALL
SELECT -5, -3, 'INTERN' FROM DUAL UNION ALL
SELECT -6, -4, 'NOVICE' FROM DUAL
) WHERE NOT EXISTS(SELECT * FROM AUTHORITY);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAP_AUTHORITY_USER CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE MAP_AUTHORITY_USER
(
    ID           NUMBER(19) PRIMARY KEY,
    AUTHORITY_ID NUMBER(19) NOT NULL,
    USER_ID      NUMBER(19) NOT NULL,
    -- auditors
    REMOVAL      CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR      VARCHAR2(32) ,
    UPDATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER      VARCHAR2(32)
);
COMMENT ON TABLE MAP_AUTHORITY_USER IS '사용자-권한 매핑';

INSERT INTO MAP_AUTHORITY_USER (ID, USER_ID, AUTHORITY_ID) SELECT * FROM (
SELECT -1 AS A, -1 AS B, -2 AS C FROM DUAL UNION ALL
SELECT -2 AS A, -1 AS B, -6 AS C FROM DUAL UNION ALL
SELECT -3 AS A, -2 AS B, -4 AS C FROM DUAL
) WHERE NOT EXISTS (SELECT * FROM MAP_AUTHORITY_USER);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAP_AUTHORITY_TEAM CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE MAP_AUTHORITY_TEAM
(
    ID           NUMBER(19) PRIMARY KEY,
    AUTHORITY_ID NUMBER(19) NOT NULL,
    TEAM_ID      NUMBER(19) NOT NULL,
    -- auditors
    REMOVAL      CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR      VARCHAR2(32) ,
    UPDATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER      VARCHAR2(32)
);
COMMENT ON TABLE MAP_AUTHORITY_TEAM IS '부서-권한 매핑';

--
-- Menu Entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MENU CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE MENU
(
    ID       NUMBER(19) PRIMARY KEY,
    PID      NUMBER(19),
    NAME     VARCHAR2(256) NOT NULL,
    NAME_AID VARCHAR2(256),
    URI      VARCHAR2(256),
    DSC      VARCHAR2(1024),
    ORD      NUMBER(10)       DEFAULT 0,
    BADGE    VARCHAR2(16),
    ICON     VARCHAR2(64),
    ATTR     VARCHAR2(512),
    OPENED   TIMESTAMP,
    -- auditors
    REMOVAL  CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR  VARCHAR2(32) ,
    UPDATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER  VARCHAR2(32)
);
COMMENT ON TABLE MENU IS '메뉴';
COMMENT ON COLUMN MENU.PID IS '상위(부모) ID';
COMMENT ON COLUMN MENU.NAME_AID IS '보조 이름';
COMMENT ON COLUMN MENU.DSC IS '설명';
COMMENT ON COLUMN MENU.ORD IS '순서';
COMMENT ON COLUMN MENU.ATTR IS '속성';
COMMENT ON COLUMN MENU.OPENED IS '개방일시';

INSERT INTO MENU (ID, NAME, NAME_AID, URI, ORD, DSC, PID) SELECT * FROM (
SELECT -999, 'Documentation', 'Documentations', '', 999, 'Usage guides for everything you need to know about it', null FROM DUAL UNION ALL
SELECT -992, 'Core Features', 'Core Features', '/documentation/features', 2, '', -999 FROM DUAL UNION ALL
SELECT -991, 'Guides', 'Guides', '/documentation/guides', 1, '', -999 FROM DUAL UNION ALL
SELECT -990, 'Changelog', 'Changelog', '/documentation/changelog', 0, '', -999 FROM DUAL UNION ALL
SELECT -906, 'Inactive Item', 'Inactive Item', '', 3, '', -900 FROM DUAL UNION ALL
SELECT -905, 'Inactive Item', 'Inactive Item', '', 3, '', -900 FROM DUAL UNION ALL
SELECT -904, 'Round badge', 'Round badge', '', 2, '', -901 FROM DUAL UNION ALL
SELECT -903, 'Rectangle badge', 'Rectangle badge', '', 1, '', -901 FROM DUAL UNION ALL
SELECT -902, 'Circle badge', 'Circle badge', '', 0, '', -901 FROM DUAL UNION ALL
SELECT -901, 'badges', 'badges', '', 0, '', -900 FROM DUAL UNION ALL
SELECT -900, 'Navigation Features', 'Navigation Features', '', 900,'Collapsable levels and badge styles at menu item', null FROM DUAL UNION ALL
SELECT -33, 'Colors', 'Colors', '/user-interface/colors', 4, '', -25 FROM DUAL UNION ALL
SELECT -32, 'Cards', 'Cards', '/user-interface/cards', 3, '', -25 FROM DUAL UNION ALL
SELECT -31, 'Icons', 'Icons', '/user-interface/icons', 2, '', -25 FROM DUAL UNION ALL
SELECT -30, 'Wizards', 'Wizards', '/user-interface/form/wizards', 2, '', -27 FROM DUAL UNION ALL
SELECT -29, 'Layouts', 'Layouts', '/user-interface/form/layouts', 1, '', -27 FROM DUAL UNION ALL
SELECT -28, 'Fields', 'Fields', '/user-interface/form/fields', 0, '', -27 FROM DUAL UNION ALL
SELECT -27, 'Form', 'Form', '', 1, '', -25 FROM DUAL UNION ALL
SELECT -26, 'Animation', 'Animation', '/user-interface/animation', 0, '', -25 FROM DUAL UNION ALL
SELECT -25, 'User Interface', 'User Interface', '', 4, 'Building elements of UI/UX', 0 FROM DUAL UNION ALL
SELECT -24, 'Split screen', 'Sign up', '/pages/authentication/login/split-screen', 1, '', -22 FROM DUAL UNION ALL
SELECT -23, 'Fullscreen', 'Sign up', '/pages/authentication/login/fullscreen', 0, '', -22 FROM DUAL UNION ALL
SELECT -22, 'Screen Play', 'Sign up', '', 1, '', -20 FROM DUAL UNION ALL
SELECT -21, 'Classic', 'Sign up', '/pages/authentication/login/classic', 0, '', -20 FROM DUAL UNION ALL
SELECT -20, 'Login', 'Login', '', 1, '', -10 FROM DUAL UNION ALL
SELECT -19, 'Modern', 'Modern', '/pages/authentication/sign-up/modern', 1, '', -17 FROM DUAL UNION ALL
SELECT -18, 'Classic', 'Classic', '/pages/authentication/sign-up/classic', 0, '', -17 FROM DUAL UNION ALL
SELECT -17, 'Sign up', 'Sign up', '', 0, '', -10 FROM DUAL UNION ALL
SELECT -16, 'Internal server error', 'Internal server error', '', 1, '', -14 FROM DUAL UNION ALL
SELECT -15, 'Page not found', 'Page not found', '', 0, '', -14 FROM DUAL UNION ALL
SELECT -14, 'Errors', 'Errors', '', 4, '', -9 FROM DUAL UNION ALL
SELECT -13, 'Support', 'Support', '/pages/support', 3, '', -9 FROM DUAL UNION ALL
SELECT -12, 'Home', 'Home', '/pages/home', 2, '', -9 FROM DUAL UNION ALL
SELECT -11, 'Help center', 'Help center', '/pages/help-center', 1, '', -9 FROM DUAL UNION ALL
SELECT -10, 'Authentication', 'Authentication', '', 0, '', -9 FROM DUAL UNION ALL
SELECT -9, 'Pages', 'Pages', '', 3, '', 0 FROM DUAL UNION ALL
SELECT -8, 'Analytics', 'Analytics', '/dashboard/analytics', 0, '', -7 FROM DUAL UNION ALL
SELECT -7, 'Dashboard', 'Dashboard', '', 2, 'Analytics for system performances!', 0 FROM DUAL UNION ALL
SELECT -6, 'Menu', 'Menu', '/system/menu', 1, '', -4 FROM DUAL UNION ALL
SELECT -5, 'User', 'User', '/system/user', 0, 'approve new user, denied, etc.', -4 FROM DUAL UNION ALL
SELECT -4, 'System', 'System', '', 1, 'Operating environment of system', 0 FROM DUAL UNION ALL
SELECT -3, 'Approve Process', 'Approve Process', '/work/approve-process', 1, '', -1 FROM DUAL UNION ALL
SELECT -2, 'Receipt', 'Receipt', '/work/receipt', 0, '', -1 FROM DUAL UNION ALL
SELECT -1, 'Main Works', 'Main Works', '', 0, 'Remember an earning yours meal!', 0 FROM DUAL UNION ALL
SELECT  0, 'Back-office Menu', '', '', 0, '', null FROM DUAL
) WHERE NOT EXISTS (SELECT * FROM MENU);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE MAP_AUTHORITY_MENU CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE MAP_AUTHORITY_MENU
(
    ID           NUMBER(19) PRIMARY KEY,
    AUTHORITY_ID NUMBER(19) NOT NULL,
    MENU_ID      NUMBER(19) NOT NULL,
    -- auditors
    REMOVAL      CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR      VARCHAR2(32) ,
    UPDATED      TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER      VARCHAR2(32)
);
COMMENT ON TABLE MAP_AUTHORITY_MENU IS '메뉴-권한 매핑';


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE CODE CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE CODE
(
    ID       NUMBER(19) PRIMARY KEY,
    GRP  VARCHAR2(256) NOT NULL,
    CODE      VARCHAR2(256) NOT NULL,
    NAME VARCHAR2(256),
    ORD      NUMBER(10)       DEFAULT 0,
    DSC      VARCHAR2(512),
    USE      CHAR(1)   DEFAULT 'Y' CHECK (USE = 'Y' OR USE = 'N'),
    -- auditors
    REMOVAL  CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR  VARCHAR2(32) ,
    UPDATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER  VARCHAR2(32)
);
COMMENT ON TABLE CODE IS '공통코드';
COMMENT ON COLUMN CODE.GRP IS '그룹(상위) 코드';
COMMENT ON COLUMN CODE.CODE IS '코드';
COMMENT ON COLUMN CODE.NAME IS '코드 이름';
COMMENT ON COLUMN CODE.ORD IS '순서';
COMMENT ON COLUMN CODE.DSC IS '설명';

INSERT INTO CODE (ID, GRP, CODE, NAME, ORD, DSC) SELECT * FROM (
SELECT 0, 'SYS', 'SYSTEMS', '시스템 그룹', 9999, '' FROM DUAL UNION ALL
SELECT -1, 'SYSTEMS', 'SITE_A', '사이트 A', 0, '' FROM DUAL UNION ALL
SELECT -2, 'SYSTEMS', 'SITE_B', '사이트 B', 1, '' FROM DUAL UNION ALL
SELECT -3, 'SYSTEMS', 'SITE_C', '사이트 C', 2, '' FROM DUAL UNION ALL
SELECT -4, 'SYSTEMS', 'SITE_D', '사이트 D', 3, '' FROM DUAL UNION ALL
SELECT -5, 'SITE_A', 'SAMPLE', '직급', 0, '' FROM DUAL UNION ALL
SELECT -6, 'SAMPLE', '004', 'executive director', 0, '' FROM DUAL UNION ALL
SELECT -7, 'SAMPLE', '005', 'director', 0, '' FROM DUAL UNION ALL
SELECT -8, 'SAMPLE', '006', 'department manager', 0, '' FROM DUAL UNION ALL
SELECT -9, 'SAMPLE', '008', 'Deputy General Manager', 0, '' FROM DUAL UNION ALL
SELECT -10, 'SAMPLE', '003', 'vice-president', 0, '' FROM DUAL UNION ALL
SELECT -11, 'SAMPLE', '002', 'representative', 0, '' FROM DUAL UNION ALL
SELECT -12, 'SAMPLE', '001', 'CEO', 0, '' FROM DUAL UNION ALL
SELECT -13, 'SAMPLE', '010', 'Assistant Manager', 0, '' FROM DUAL UNION ALL
SELECT -14, 'SAMPLE', '007', 'Head of team', 0, '' FROM DUAL UNION ALL
SELECT -15, 'SAMPLE', '012', 'Staff', 0, '' FROM DUAL UNION ALL
SELECT -16, 'SAMPLE', '009', 'Manager', 0, '' FROM DUAL UNION ALL
SELECT -17, 'SAMPLE', '011', 'Senior staff', 0, '' FROM DUAL UNION ALL
SELECT -18, 'SITE_A', 'FRUIT', '과일', 0, '' FROM DUAL UNION ALL
SELECT -19, 'FRUIT', '001', '수박', 0, '' FROM DUAL UNION ALL
SELECT -20, 'FRUIT', '002', '참외', 1, '' FROM DUAL UNION ALL
SELECT -21, 'FRUIT', '003', '복숭아', 2, '' FROM DUAL
) WHERE NOT EXISTS (SELECT * FROM CODE);

--
-- File entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE " CASCADE CONSTRAINTS FILE"';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE "FILE"
(
    ID      VARCHAR2(128) PRIMARY KEY,
    NAME    VARCHAR2(256) NOT NULL,
    PATH    VARCHAR2(512) NOT NULL,
    "SIZE"    NUMBER(19)    DEFAULT 0,
    MIME    VARCHAR2(128),
    READ  NUMBER(19)    DEFAULT 0,
    PACK    VARCHAR2(64) DEFAULT 'NONE',
    ORD     NUMBER(10),
    -- auditors
    REMOVAL CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR VARCHAR2(32) ,
    UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER VARCHAR2(32)
);

CREATE INDEX FILE_PACK_IX ON "FILE" (PACK);
COMMENT ON TABLE "FILE" IS '첨부파일';
COMMENT ON COLUMN "FILE".NAME IS '원본 파일명';
COMMENT ON COLUMN "FILE".PATH IS '저장 경로';
COMMENT ON COLUMN "FILE".SIZE IS '파일 크기';
COMMENT ON COLUMN "FILE".MIME IS 'Content-Type(or Mime-Type)';
COMMENT ON COLUMN "FILE".READ IS '다운로드 횟수';
COMMENT ON COLUMN "FILE".PACK IS '파일 묶음';
COMMENT ON COLUMN "FILE".ORD IS '파일 정렬 순서';


--
-- Article Entity
--
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ARTICLE_CATEGORY CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE ARTICLE_CATEGORY
(
    CATEGORY VARCHAR2(64) PRIMARY KEY,
    TYPE     VARCHAR2(64),
    DSC      VARCHAR2(4000),
    PROPS    CLOB,
    REMOVAL  CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR  VARCHAR2(32) ,
    UPDATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER  VARCHAR2(32)
);
COMMENT ON TABLE ARTICLE_CATEGORY IS '게시글 분류';
COMMENT ON COLUMN ARTICLE_CATEGORY.TYPE IS '유형(일반게시판/공지사항/자료실 등등)';
COMMENT ON COLUMN ARTICLE_CATEGORY.DSC IS '설명';
COMMENT ON COLUMN ARTICLE_CATEGORY.PROPS IS '속성(JSON)';
INSERT INTO ARTICLE_CATEGORY (CATEGORY, TYPE, DSC, PROPS) VALUES ('NOTICE', '', '', CAST('{"page": {"size": 12, "indices": 5}, "usage": {"reply": true, "comment": true, "defaultSecret": false}}' AS CLOB));


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ARTICLE CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE ARTICLE
(
    ID       NUMBER(19) PRIMARY KEY,
    BID      NUMBER(19),
    ORD      NUMBER(10)       DEFAULT 0,
    DEPTH    NUMBER(10)       DEFAULT 0,
    CATEGORY VARCHAR2(64) NOT NULL,
    USER_ID  NUMBER(19),
    AUTHOR   VARCHAR2(64),
    EMAIL    VARCHAR2(256),
    PASSWORD VARCHAR2(256),
    SECRET   CHAR(1)   DEFAULT 'N' CHECK (SECRET = 'Y' OR SECRET = 'N'),
    READ     NUMBER(19)    DEFAULT 0,
    TITLE    VARCHAR2(1024),
    CONTENT  CLOB,
    FULLTEXT CLOB,
    EXTRA    CLOB,
    -- auditors
    REMOVAL  CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR  VARCHAR2(32) ,
    UPDATED  TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER  VARCHAR2(32)
);
COMMENT ON TABLE ARTICLE IS '게시글';
COMMENT ON COLUMN ARTICLE.BID IS '답글용 묶음 ID';
COMMENT ON COLUMN ARTICLE.ORD IS '답글 정렬 순서';
COMMENT ON COLUMN ARTICLE.DEPTH IS '답글 깊이';
COMMENT ON COLUMN ARTICLE.CATEGORY IS '게시글 분류';
COMMENT ON COLUMN ARTICLE.SECRET IS '비밀글';
COMMENT ON COLUMN ARTICLE.READ IS '조횟수';
COMMENT ON COLUMN ARTICLE.FULLTEXT IS '문자화된 내용(HTML 태그 제거, 텍스트 검색 용)';
COMMENT ON COLUMN ARTICLE.EXTRA IS '부가정보(JSON)';


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ARTICLE_COMMENT CASCADE CONSTRAINTS ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;

CREATE TABLE ARTICLE_COMMENT
(
    ID         NUMBER(19) PRIMARY KEY,
    BID        NUMBER(19),
    ORD        NUMBER(10)       DEFAULT 0,
    DEPTH      NUMBER(10)       DEFAULT 0,
    ARTICLE_ID NUMBER(19) NOT NULL,
    USER_ID    NUMBER(19),
    AUTHOR     VARCHAR2(64),
    EMAIL      VARCHAR2(256),
    PASSWORD   VARCHAR2(256),
    CONTENT    VARCHAR2(4000),
    SECRET     CHAR(1)   DEFAULT 'N' CHECK (SECRET = 'Y' OR SECRET = 'N'),
    -- auditors
    REMOVAL    CHAR(1)   DEFAULT 'N'  CHECK (REMOVAL = 'Y' OR REMOVAL = 'N'),
    CREATED    TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CREATOR    VARCHAR2(32) ,
    UPDATED    TIMESTAMP DEFAULT SYSTIMESTAMP ,
    UPDATER    VARCHAR2(32)
);
COMMENT ON TABLE ARTICLE_COMMENT IS '게시글 댓글';
COMMENT ON COLUMN ARTICLE_COMMENT.BID IS '묶음 ID';
COMMENT ON COLUMN ARTICLE_COMMENT.ORD IS '정렬 순서';
COMMENT ON COLUMN ARTICLE_COMMENT.DEPTH IS '답글 깊이';
COMMENT ON COLUMN ARTICLE_COMMENT.ARTICLE_ID IS '게시물 ID';
COMMENT ON COLUMN ARTICLE_COMMENT.AUTHOR IS '작성자 이름';
COMMENT ON COLUMN ARTICLE_COMMENT.EMAIL IS '이메일';
COMMENT ON COLUMN ARTICLE_COMMENT.PASSWORD IS '비밀번호';
COMMENT ON COLUMN ARTICLE_COMMENT.SECRET IS '비밀글';


ALTER TABLE USR
	ADD CONSTRAINT USR_TEAM_FK1
		FOREIGN KEY (TEAM_ID) REFERENCES TEAM;

ALTER TABLE MAP_USER_TEAM
	ADD CONSTRAINT MAP_USER_TEAM_FK1
		FOREIGN KEY (USER_ID) REFERENCES USR;

ALTER TABLE MAP_USER_TEAM
	ADD CONSTRAINT MAP_USER_TEAM_FK2
		FOREIGN KEY (TEAM_ID) REFERENCES TEAM;

ALTER TABLE MAP_AUTHORITY_USER
	ADD CONSTRAINT MAP_AUTHORITY_FK1_USER
		FOREIGN KEY (USER_ID) REFERENCES USR;

ALTER TABLE MAP_AUTHORITY_USER
	ADD CONSTRAINT MAP_AUTHORITY_FK2_USER
		FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY;

ALTER TABLE MAP_AUTHORITY_TEAM
	ADD CONSTRAINT MAP_AUTHORITY_FK1_TEAM
		FOREIGN KEY (TEAM_ID) REFERENCES TEAM;

ALTER TABLE MAP_AUTHORITY_TEAM
	ADD CONSTRAINT MAP_AUTHORITY_FK2_TEAM
		FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY;

ALTER TABLE MAP_AUTHORITY_MENU
	ADD CONSTRAINT MAP_AUTHORITY_FK1_MENU
		FOREIGN KEY (MENU_ID) REFERENCES MENU;

ALTER TABLE MAP_AUTHORITY_MENU
	ADD CONSTRAINT MAP_AUTHORITY_FK2_MENU
		FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY;

ALTER TABLE CODE
	ADD CONSTRAINT CODE_UK1
		UNIQUE (GRP, CODE);

ALTER TABLE ARTICLE
    ADD CONSTRAINT ARTICLE_FK1
        FOREIGN KEY (USER_ID) REFERENCES USR (ID);

ALTER TABLE ARTICLE_COMMENT
    ADD CONSTRAINT ARTICLE_COMMENT_FK1
        FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE;
